### PR TITLE
Migrate the Extension to Visual Studio 2017

### PR DESCRIPTION
**Pull request by moesoha**

### CODE REVIEW

**Comment by moesoha** [comment]
@ThadHouse can u merge this pr to the master branch? it will make the extension suit for VS2017. I haven't found bug since i upgraded to VS2017 with the extension.

**Comment by ThadHouse** [comment]
I am actually completely rebuilding the extension this summer. It's going to share code with the new .NET CLI plugin I made, and support only VS 2017. That way I only have to test and maintain 1 deployment code base.

**Comment by moesoha** [comment]
okay... i know the FRC-CLI is under developing. I just want a temporary solution. I like RobotDotNet very much, I uploaded a video which introduced my team's RobotCode coded in C# on a Chinese website, and I highlighted how great RobotDotNet is. 
I will keep following up FRC-CLI and hoping I can help on something.

**Comment by ThadHouse** [comment]
This failed to publish, so I reverted it

**Comment by moesoha** [comment]
Glad to see updates in this repo. I'll check what's wrong with it.

**Pull request merged**
